export const categories = [
    { id: 'vegetables', name: 'Vegetables', count: 120 },
    { id: 'fruits', name: 'Fruits', count: 90 },
    { id: 'dairy', name: 'Dairy', count: 45 },
    { id: 'bakery', name: 'Bakery', count: 60 },
    { id: 'pantry', name: 'Pantry', count: 80 },
];

export const brands = [
    { id: 'farmfresh', name: 'FarmFresh', logo: '🌾' },
    { id: 'tropic', name: 'TropicGold', logo: '🥭' },
    { id: 'meadow', name: 'MeadowDairy', logo: '🥛' },
    { id: 'artisan', name: 'ArtisanBake', logo: '🍞' },
];

export const products = [
    {
        id: 1,
        name: 'Organic Cambodian Mango',
        code: 'FRU-001',
        price: 4.99,
        oldPrice: 6.99,
        image: 'https://images.unsplash.com/photo-1553279768-865021837e9b',
        rating: 4.8,
        reviews: 124,
        badge: 'Sale',
        inStock: true,
        category: 'fruits',
        brand: 'tropic',
    },
    {
        id: 2,
        name: 'Fresh Morning Glory',
        code: 'VEG-012',
        price: 1.49,
        image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999',
        rating: 4.5,
        reviews: 89,
        badge: 'New',
        inStock: true,
        category: 'vegetables',
        brand: 'farmfresh',
    },
    {
        id: 3,
        name: 'Farm Eggs (12 pack)',
        code: 'DAI-008',
        price: 3.25,
        image: 'https://images.unsplash.com/photo-1582722872405-2c03e42f8d83',
        rating: 4.9,
        reviews: 210,
        badge: 'Hot',
        inStock: true,
        category: 'dairy',
        brand: 'meadow',
    },
    {
        id: 4,
        name: 'Artisan Sourdough Loaf',
        code: 'BAK-003',
        price: 5.5,
        image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff',
        rating: 4.6,
        reviews: 67,
        inStock: false,
        category: 'bakery',
        brand: 'artisan',
    },
    {
        id: 5,
        name: 'Organic Red Apples',
        code: 'FRU-014',
        price: 3.99,
        oldPrice: 5.49,
        image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6',
        rating: 4.7,
        reviews: 156,
        badge: 'Sale',
        inStock: true,
        category: 'fruits',
        brand: 'tropic',
    },
    {
        id: 6,
        name: 'Baby Spinach Bundle',
        code: 'VEG-021',
        price: 2.25,
        image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb',
        rating: 4.4,
        reviews: 72,
        inStock: true,
        category: 'vegetables',
        brand: 'farmfresh',
    },
    {
        id: 7,
        name: 'Raw Wildflower Honey',
        code: 'PAN-002',
        price: 8.99,
        image: 'https://images.unsplash.com/photo-1587049352846-4a03e04c0e42',
        rating: 4.9,
        reviews: 98,
        inStock: true,
        category: 'pantry',
        brand: 'farmfresh',
    },
    {
        id: 8,
        name: 'Coconut Water (6-pack)',
        code: 'BEV-005',
        price: 6.5,
        oldPrice: 7.99,
        image: 'https://images.unsplash.com/photo-1537641110795-63ac2372f544',
        rating: 4.3,
        reviews: 44,
        badge: 'Sale',
        inStock: true,
        category: 'pantry',
        brand: 'tropic',
    },
];
